#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# PHP语法检查
set -e
changed_files=`git diff-index --cached --name-only $against --`
for f in $changed_files ;do
    ext=${f##*.}
    if test "$ext" = "php" ;then
        if test -e "$f";then
            php -l -n $f
        fi
    fi
done